###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'Lawrence S. Moss'
bibtex_bibfiles = ['references.bib']
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2023'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'Thumbs.db', '_build']
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'sphinx_exercise', 'sphinx_proof', 'sphinxcontrib.bibtex', 'sphinx_jupyterbook_latex']
external_toc_exclude_missing = False
external_toc_path = '_toc.yml'
html_baseurl = ''
html_favicon = ''
html_logo = 'beaver.jpg'
html_sourcelink_suffix = ''
html_theme = 'sphinx_book_theme'
html_theme_options = {'search_bar_text': 'Search this book...', 'launch_buttons': {'notebook_interface': 'classic', 'binderhub_url': '', 'jupyterhub_url': '', 'thebe': False, 'colab_url': ''}, 'path_to_docs': 'docs', 'repository_url': 'https://github.com/lmoss/onesharp', 'repository_branch': 'main', 'extra_footer': '', 'home_page_in_toc': True, 'announcement': '', 'analytics': {'google_analytics_id': ''}, 'use_repository_button': True, 'use_edit_page_button': False, 'use_issues_button': True}
html_title = 'Invitation to Computability'
latex_engine = 'pdflatex'
mathjax3_config = {'tex': {'macros': {'quadiff': ['\\quad\\mbox{iff}\\quad'], 'quadeq': ['\\quad =\\quad'], 'dar': ['\\downarrow'], 'uar': ['\\uparrow'], 'eps': ['\\varepsilon'], 'id': ['id'], 'o': ['\\circ'], 'N': '\\mathbb{N}', 'set': ['\\left\\{#1\\right\\}', 1], 'one': ['\\mathtt{1}'], 'hash': ['\\mathtt{\\#}'], 'diag': ['\\mathtt{diag}'], 'self': ['\\mathtt{self}'], 'copyprog': ['\\mathtt{copy}'], 'clearprog': ['\\mathtt{clear}'], 'writeprog': ['\\mathtt{write}'], 'writetotwo': ['\\mathtt{write}_2'], 'semantics': ['[\\![#1]\\!]', 1], 'semanticsalt': ['\\langle\\!\\langle #1\\rangle\\!\\rangle', 1], 'moveprog': ['\\mathtt{move}'], 'moveprogtwoone': ['\\mathtt{move}_{2,1}'], 'phifn': ['\\varphi'], 'Tile': ['\\mathit{Tile}'], 'TT': ['\\mathcal{T}'], 'DD': ['\\mathcal{D}'], 'Rone': ['R1'], 'Rtwo': ['R2'], 'words': ['\\mbox{words}']}}}
mathjax_path = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'
myst_enable_extensions = ['dollarmath', 'amsmath', 'colon_fence', 'deflist']
myst_url_schemes = ['mailto', 'http', 'https']
nb_execution_allow_errors = False
nb_execution_cache_path = ''
nb_execution_excludepatterns = []
nb_execution_in_temp = False
nb_execution_mode = 'off'
nb_execution_timeout = 30
nb_output_stderr = 'show'
numfig = True
pygments_style = 'sphinx'
suppress_warnings = ['myst.domains']
use_jupyterbook_latex = True
use_multitoc_numbering = True
