#!/usr/bin/env python3
"""
insert_macros.py

Inserts (or updates) a hidden LaTeX macro-definition cell at the top of every
Jupyter notebook in a folder, so that platforms which don't read _config.yml
(Google Colab, CoCalc, plain nbviewer, etc.) still render your custom macros
correctly.

USAGE:
    python insert_macros.py PATH [PATH ...] [--dry-run]

    PATH can be a single .ipynb file or a directory (searched recursively).
    --dry-run shows what would change without writing any files.

HOW TO UPDATE YOUR MACROS LATER:
    Just edit the MACROS dictionary below to match your _config.yml's
    mathjax3_config -> tex -> macros section, then rerun this script over
    your notebooks folder. The script finds its own previously-inserted
    block (marked by the AUTO-MACROS comments) and replaces it in place,
    so rerunning is always safe -- it will never create duplicates.
"""

import json
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# 1. Keep this in sync with the "macros" section of your _config.yml.
#    Zero-argument macros are a plain string.
#    Macros that take arguments are [replacement, number_of_args].
# ---------------------------------------------------------------------------
MACROS = {
    "quadiff": ["\\quad\\mbox{iff}\\quad"],
    "quadeq": ["\\quad =\\quad"],
    "dar": ["\\downarrow"],
    "uar": ["\\uparrow"],
    "eps": ["\\varepsilon"],
    "id": ["id"],
    "o": ["\\circ"],
    "N": "\\mathbb{N}",
    "set": ["\\left\\{#1\\right\\}", 1],
    "one": ["\\mathtt{1}"],
    "onett": ["\\mathtt{1}"],
    "hash": ["\\mathtt{\\#}"],
    "onehash": ["\\onett\\hash"],
    "onesharp": ["\\mathtt{1\\#}"],
    "diag": ["\\mathtt{diag}"],
    "self": ["\\mathtt{self}"],
    "diagprog": ["\\mathtt{diag}"],
    "selfprog": ["\\mathtt{self}"],
    "copyprog": ["\\mathtt{copy}"],
    "uprog": ["\\mathtt{u}"],
    "clearprog": ["\\mathtt{clear}"],
    "reverseprog": ["\\mathtt{reverse}"],
    "writeprog": ["\\mathtt{write}"],
    "writetotwo": ["\\mathtt{write}_2"],
    "tradeprog": ["\\mathtt{trade}"],
    "tidyprog": ["\\mathtt{tidy}"],
    "semantics": ["[\\![#1]\\!]", 1],
    "semanticsalt": ["\\langle\\!\\langle #1\\rangle\\!\\rangle", 1],
    "moveprog": ["\\mathtt{move}"],
    "moveprogtwoone": ["\\mathtt{move}_{2,1}"],
    "phifn": ["\\varphi"],
    "Tile": ["\\mathit{Tile}"],
    "TT": ["\\mathcal{T}"],
    "DD": ["\\mathcal{D}"],
    "Rone": ["R1"],
    "Rtwo": ["R2"],
    "words": ["\\mbox{words}"],
    "Words": ["\\textit{words}"],
    "Rings": ["\\mathsf{Rings}"],
    "iif": ["\\rightarrow"],
    "andd": ["\\wedge"],
    "proves": ["\\vdash"],
    "xbar": ["\\overline{x}"],
    "ybar": ["\\overline{y}"],
    "Ronesharp": ["R\\onesharp"],
}

START_MARKER = "<!-- AUTO-MACROS-START (generated by insert_macros.py, do not edit by hand) -->"
END_MARKER = "<!-- AUTO-MACROS-END -->"


def build_macro_cell_source():
    """Turn MACROS into a markdown cell's source lines (nbformat wants a list of strings)."""
    lines = [START_MARKER + "\n", "$$\n"]
    for name, spec in MACROS.items():
        if isinstance(spec, str):
            replacement, nargs = spec, 0
        elif len(spec) == 1:
            replacement, nargs = spec[0], 0
        else:
            replacement, nargs = spec[0], spec[1]

        if nargs == 0:
            lines.append(f"\\gdef\\{name}{{{replacement}}}\n")
        else:
            args = "".join(f"#{i}" for i in range(1, nargs + 1))
            lines.append(f"\\gdef\\{name}{args}{{{replacement}}}\n")
    lines.append("$$\n")
    lines.append(END_MARKER)
    return lines


def make_macro_cell():
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": build_macro_cell_source(),
    }


def process_notebook(path: Path, dry_run: bool) -> bool:
    """Returns True if the notebook was (or would be) changed."""
    with open(path, "r", encoding="utf-8") as f:
        nb = json.load(f)

    cells = nb.get("cells", [])
    new_cell = make_macro_cell()

    # Look for an existing auto-generated macro cell (anywhere, though we
    # always put it first) so reruns update in place instead of duplicating.
    existing_index = None
    for i, cell in enumerate(cells):
        source = cell.get("source", [])
        joined = "".join(source) if isinstance(source, list) else source
        if START_MARKER in joined:
            existing_index = i
            break

    if existing_index is not None:
        if cells[existing_index] == new_cell:
            return False  # already up to date
        cells[existing_index] = new_cell
    else:
        cells.insert(0, new_cell)

    nb["cells"] = cells

    if not dry_run:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(nb, f, indent=1, ensure_ascii=False)
            f.write("\n")

    return True


def find_notebooks(paths):
    for p in paths:
        p = Path(p)
        if p.is_file() and p.suffix == ".ipynb":
            yield p
        elif p.is_dir():
            for nb_path in sorted(p.rglob("*.ipynb")):
                if ".ipynb_checkpoints" in nb_path.parts:
                    continue
                if "_build" in nb_path.parts:
                    continue
                yield nb_path


def main():
    args = sys.argv[1:]
    dry_run = "--dry-run" in args
    args = [a for a in args if a != "--dry-run"]

    if not args:
        print(__doc__)
        sys.exit(1)

    changed = []
    unchanged = []
    for nb_path in find_notebooks(args):
        if process_notebook(nb_path, dry_run):
            changed.append(nb_path)
        else:
            unchanged.append(nb_path)

    verb = "Would update" if dry_run else "Updated"
    for p in changed:
        print(f"{verb}: {p}")
    print(f"\n{verb} {len(changed)} notebook(s); {len(unchanged)} already up to date.")
    if dry_run:
        print("(Dry run -- no files were actually written. Rerun without --dry-run to apply.)")


if __name__ == "__main__":
    main()
